pipeline {
agent any

parameters{
choice(name: 'env', choices: 'DEV\nTEST', description: 'Select Environment')
choice(name: 'action' choices: 'init\nplan\napply\nplan-destroy\ndestroy', description: 'Select action' )
}
stages{
 stage()
}
}
